MODEL:
  NAME: EfficientSAM3
  PRETRAINED: ''
  RESUME: ''

TRAIN:
  EPOCHS: 30
  BASE_LR: 5.0e-4
  WARMUP_LR: 5.0e-7
  MIN_LR: 5.0e-6
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 5.0
  FIND_UNUSED_PARAMETERS: False

DATA:
  IMG_SIZE: 1008
  DATASET: sa1b
  DATA_PATH: data/sa-1b/
  BATCH_SIZE: 64
  NUM_WORKERS: 8

DISTILL:
  EMBED_DIM: 256
  EMBED_SIZE: 64
  TEACHER_EMBED_PATH: output/stage1_teacher/embeddings/
  NO_RAND: True
  PIXEL_WISE: 1.0

OUTPUT: output/stage1
TAG: default
AMP_ENABLE: True


